presets:
  global:
    include:
      - bittorrent.yml
      - presets/global.yml
    
  tv-global:
    include:
      - presets/tv-global.yml
    
tasks:
  tv-parent:
    include:
      - tasks/tv-parent.yml
  tv-children:
    include:
      - tasks/tv-children.yml